spring:
  main:
    banner-mode: off
    log-startup-info: false
  datasource:
    url: jdbc:mysql://localhost:3306/cash?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: cashuser
    password: 123456789
logging:
  level:
    root: warn
    com.xinyan: debug
mybatis:
  mapper-locations: classpath:/mapper/**Mapper.xml
  configuration:
    # underscore: 下划线
    # camel: 骆驼
    # camel-case: 驼峰形式
    map-underscore-to-camel-case: true